[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"

# Standard Optimizer Settings
optimizer = true
optimizer_runs = 200

# Permissions
fs_permissions = [{ access = "read", path = "./" }]

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
]

[fuzz]
runs = 256
max_test_rejects = 65536

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"

# FIXED: Changed [ci] to [profile.ci] to fix the warning
[profile.ci]
runs = 1000
